### ISSUE TITLE
Crate name

### ISSUE THREAD

**Issue by abimek** [jsaied99/pinecone-rust-client#1]
Hello! I saw that this crate was yanked. I have a pinecone client for wasm but was hoping to make it a more general pinecone client. I was wondering if you were willing to transfer the name. If not that's ok.

**Comment by abimek** [comment]
Nvm.

**Comment by abimek** [comment]
Nvm

**Comment by jsaied99** [comment]
You sure, I don't mind really.

**Comment by abimek** [comment]
Yea I decided to name it pinenut! All good though thank you for responding.
